[tool.poetry]
name = "glorious"
version = "1.0.0"
description = "Python bindings for Arithmetic Coding with Context"
authors = ["Andy Chen"]
packages = [{ include = "glorious", from = "src" }]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
python = "^3.11.0"
openai = "^1.45.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pre-commit = "^2.20.0"

[tool.poetry.scripts]
markdown_tree = "scripts.markdown_tree:main"
ai_commit = "scripts.autocommit:main"
