# rust-toolchain.toml
[toolchain]
channel = "stable"
components = ["rust-src"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "aarch64-apple-darwin",
]
